---
- name: Provision a new Ubuntu 18.04 server with hardened SSH settings and install some prerequisite tool packages
  hosts: all
  become: true

  vars_files:
    - vars_provision_server.yml

  roles:
    - timezone
    - user
    - packages
    - ssh
    ##- iptables
    - fail2ban
