---
- name: "Install CKAN {{ ckan_version }} and reverse proxy with NGINX"
  hosts: all
  become: true
  
  vars:
    # IMPORTANT: use _ for space character in ckan_site_name!
    ckan_site_name: ckan
    ckan_site_url: "http://192.168.1.200"
    ckan_version: 2.8.3
    ckan_src_url: "git+https://github.com/ckan/ckan.git@ckan-{{ ckan_version }}#egg=ckan"
    ckan_solr_url: "http://127.0.0.1:8983/solr/ckan"
    ckan_virtualenv: "{{ ckan_user.home_path }}/{{ ckan_site_name }}"
    ckan_conf_dir: "/etc/ckan/{{ ckan_site_name }}"
    ckan_storage_path: "/var/lib/ckan/{{ ckan_site_name }}"
    # Set ckan_debug_mode to true for debugging or false for production
    ckan_debug_mode: false
    # CKAN max resource upload size in MB
    ckan_max_resource_size: 10
    # CKAN max image upload size in MB
    ckan_max_image_size: 2
    # CKAN email settings
    ckan_email_to: "ckan@yourdomain.com"
    ckan_error_email_from: "no-reply@yourdomain.com"
    ckan_smtp_server: "smtp.yourdomain.com"
    ckan_smtp_starttls: False
    ckan_smtp_user: "ckan-mailer"
    ckan_smtp_password: 'T$UZqA\XeN$}CX8)'
    ckan_smtp_mail_from: "no-reply@yourdomain.com"
    ckan_db: {
      username: "ckan_default",
      password: "changethispassword",
      role_attr_flags: "NOSUPERUSER,NOCREATEDB,NOCREATEROLE",
      name: "ckan_default",
      host: "localhost"
    }
    ckan_user: {
      name: "ckan",
      system: "yes",
      home_path: "/usr/lib/ckan",
      shell: "/sbin/nologin",
      description: "CKAN User"
    }

  roles:
    - ckan
