---
- name: "Clone Denpasar frontend application repo from https://github.com/geoenvo/oskari-application-dps/ to `{{ install_dir_oskari }}/oskari-server/oskari-application-dps`"
  git:
    repo: https://github.com/geoenvo/oskari-application-dps.git
    dest: "{{ install_dir_oskari }}/oskari-server/oskari-application-dps"
    clone: yes
    update: yes

- name: "Ensure `{{ install_dir_oskari }}/oskari-server/oskari-application-dps` exists"
  file:
    path: "{{ install_dir_oskari }}/oskari-server/oskari-application-dps"
    state: directory

- name: Run `sudo npm install` in `{{ install_dir_oskari }}/oskari-server/oskari-application-dps`
  shell: |
    cd {{ install_dir_oskari }}/oskari-server/oskari-application-dps
    sudo npm install
    exit

- name: Run `sudo npm run build` in `{{ install_dir_oskari }}/oskari-server/oskari-application-dps`
  shell: |
    cd {{ install_dir_oskari }}/oskari-server/oskari-application-dps
    sudo npm run build
    exit

- name: "Ensure `{{ install_dir_oskari }}/oskari-server/oskari-application-dps/dist/{{ oskari_client_version }}` exists"
  file:
    path: "{{ install_dir_oskari }}/oskari-server/oskari-application-dps/dist/{{ oskari_client_version }}"
    state: directory

- name: Backup `oskari-front.xml` file if backup file `oskari-front.xml.orig` does not exist
  shell: "cp {{ install_dir_oskari }}/oskari-server/webapps/oskari-front.xml {{ install_dir_oskari }}/oskari-server/webapps/oskari-front.xml.orig"
  args:
    creates: "{{ install_dir_oskari }}/oskari-server/webapps/oskari-front.xml.orig"

- name: Copy `oskari-front.xml` settings file for Oskari from template
  template:
    src: ../templates/oskari-front.xml.j2
    dest: "{{ install_dir_oskari }}/oskari-server/webapps/oskari-front.xml"
    owner: root
    group: root
    mode: 0644
